language: node_js
node_js:
- '8'
before_deploy:
- npm run build
deploy:
  provider: npm
  email: moraneva@msu.edu
  api_key:
    secure: cePKg6JoTCCCwM0YbX62/JUoa5KyOXOXw8poWnYwF697cNyO7z7BerRZvAt49yZFn+lWZ/m6hpT7dl0TksDOZHoUjffxMlIEQFWxIodEzjjykuAxq0O37zsGLhX/tgGWgnlQf6mNe73FEaD+6Mt7HDUWMr/N3MFhIio6cZ0RO81IH+iVPk5rcNoEkGk3XwM86JJmz6PkT5i2ndpdSfNqwp46L65iCO3SsZnrnq0zXBZCmWV2jZynKFJS5PcScnd6QImmtEdt9m+AE0tC0uRLGjOW7gwK1hLDC75iEINa2VdyghyhsfRTR2gmpzbAJz5ZwSO+f5RhxVzDBN/uRZ81+YFHB7QHyk1x1hZTifyR2Pdxks3JnJY9RIwLN9bv6tuc0umwfoOEevAilpktxYtYdGm6wbYHdmZSOCOsd2g9EfGpirOSh3wSPcQKumgIq/AVvnDLs3C8B+XzYQYu7OuEl2oTm0GfildHcqcTBOhJoVl+zbsOZ2vrdfBFYTEWKNBYkzcSg4zsUGO+ge1IweSxYmvlasUZOBRYDa46nQSWO2c040DYK1/iw8LCuNSynEFQduSuwz9nrhbV6+g1dOKmBA6qyylY7F+xMRsQ+idetKSNV2Fh03PiPIREeEq+hlZtCYFLZNrBjHt/BFLJl8l13SbDFp3SeKxp8FB6Ervmzoc=
  on:
    tags: true
    branch: master
  skip_cleanup: true